[package]
name = "webserv"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
rand = "0.8"
libc = "0.2"
time = "0.3"
httpdate = "1.0"
chrono = "0.4"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"

[[bin]]
name = "webserv"
path = "src/main.rs"